name: Windows Build

on:
  release:
    types:
      - released

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Configure CMake
      run: cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -S. -B./build -G "Visual Studio 17 2022" -T host=x64 -A x64

    - name: Build
      run: cmake --build build --config Release

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/Release

  release:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: download artifact
      uses: actions/download-artifact@v3
      with:
        name: build
        path: build/Release

    - name: zip binary
      run: zip -r ./sunskin.zip ./build/Release

    - name: upload binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./sunskin.zip
        asset_name: sunskin.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
